### PR TITLE
Improve platform support

### PR DESCRIPTION
**Pull request by davnn**
Hi!

thanks for the great package. It would be great if we could provide pre-built packages for multiple platforms and Python versions and this pull request does exactly that.

Thanks,
David

### CODE REVIEW

**Comment by kno10** [comment]
Thank you, much appreciated.
However, the action does not appear to work entriely yet:
```
pypa/gh-action-pypi-publish@master
Error: Container action is only supported on Linux
```
It seems there is an additional step necessary, where the compiled artifacts are collected and (if all compiles were successful) uploaded: https://github.com/pypa/gh-action-pypi-publish/discussions/48#discussioncomment-135341

**Comment by davnn** [comment]
Sorry, I didn't see that you already worked on it. Are there any problems still?

**Comment by kno10** [comment]
It seems to work, but I need to check whether it is worth to add cross-compilation for Linux targets on other CPUs, in particular aarch64, arm. Maybe musl, and of course for Apples new M1 CPUs.

**Comment by davnn** [comment]
I believe further support will only be possible hosting your own runners, see [1, 2], or using a different CI service. Not sure if that's worth the effort.

[1] https://github.com/actions/runner/issues/805
[2] https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by kno10** [comment]
At least for linux, cross-compilation should be possible, e.g.,
https://github.com/messense/crfs-rs/blob/0e77658d65abefef8818cc25b0a57941ff41269b/.github/workflows/Python.yml#L105-L109
and there appears to be a github action docker image for osxcross, too (but it does not mention aarch64-apple-darwin for M1):
https://github.com/marketplace/actions/shogan-rust-static-build
but M1 does not appear to be perfectly supported yet by rust tooling: https://github.com/rust-lang/rust/issues/73908

**Pull request merged**
